[features]
seeds = false
skip-lint = false
[programs.localnet]
hedge_take_home = "2caX34vXoWbkVmYJmiV5HP1miKbpfhQkuWcBD13hYuKo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ixmorrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
